name: mEyeApp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  misrut_core:
    path: ../mEye

  flutter_native_splash: ^2.3.7
  go_router: ^11.1.4
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway/Raleway-Black.ttf
          weight: 900
